version: '3.8'

services:
  mongoDB:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb

volumes:
  mongodb_data:
  mongodb_logs:
